sudo: required
services:
  - docker

before_install:
  - docker build -t capsulecho0216/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true capsulecho0216/react-test yarn test

after_success:
  - docker build -t capsulecho0216/multi-client ./client
  - docker build -t capsulecho0216/multi-nginx ./nginx
  - docker build -t capsulecho0216/multi-server ./server
  - docker build -t capsulecho0216/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push capsulecho0216/multi-client
  - docker push capsulecho0216/multi-nginx
  - docker push capsulecho0216/multi-server
  - docker push capsulecho0216/multi-worker
